### ISSUE TITLE
support for crazyhouse FEN

### ISSUE THREAD

**Issue by ornicar** [niklasf/web-boardimage#1]
like `r3k2r/pp4pp/4Bp2/1p1p4/6P1/p1q1BPKP/PnP5/RQ2nB1R/PPPBnn` where `PPPBnn` are the pocket pieces, or `rnbqkbnr/pppppppp/8/8/8/2P5/PP1PPPPP/RNBQKBNR/` without pocket pieces (also failing atm)

**Comment by niklasf** [comment]
at least accepting the fens now. todo for some time: actually draw the pockets

**Comment by niklasf** [comment]
https://github.com/niklasf/lila-gif/issues/13
