### ISSUE TITLE
how to run & use this script ?

### ISSUE THREAD

**Issue by tissatussa** [niklasf/web-boardimage#8]
i think i managed to install the packages on my Xubuntu 20.04 according to your readme, but then execution fails :

```
$ pipenv install
Installing dependencies from Pipfile.lock (9e16cc)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/0 — 00:00:00
To activate this project's virtualenv, run the following:
 $ pipenv shell
```

i did not do 'pinenv shell' but i did your command but i get this error :

```
$ pipenv run server [--port 8080] [--bind 127.0.0.1]
Error: the command server could not be found within PATH or Pipfile's [scripts].
```

i was not able to tackle this error : i can not find a way to install the command 'server' .. what am i missing ?  Should a browser window open ?  I see the URL https://backscattering.de/web-boardimage/board.svg?[...] and it works, but how should this be done at localhost ?  For me, your readme lacks details ..

**Comment by niklasf** [comment]
Your `pipenv install` shows 0/0 dependencies. Try running it from the project directoy. Same for `pipenv run server`.

**Comment by tissatussa** [comment]
again i want to try this script .. now i'm on a new Xubuntu 22.04 installation, so i had to install the dependencies again .. but it doesn't work, i don't understand how to run this script on localhost .. i can give full info .. can you help ?
